---

- hosts: localhost
  tasks:
  - name: Creating a file with content
    copy:
      dest: "./var-test.yml"
      content: |
        line 01
        "line 02  date {{ ansible_date_time.date }} hour {{ ansible_date_time.hour }}  minute {{ ansible_date_time.minute }}"