---

- hosts: localhost
  tasks:
  - name: Creating a file with content
    copy:
      dest: "./var-test.yml"
      content: |
        line 01 static JP-demo
        "line 02  date {{ ansible_date_time.date }} hour {{ ansible_date_time.hour | int -5 | int }}  minute {{ ansible_date_time.minute }}"